components/user/UserPage.tsx

Fix user page to be able to see all nfts even if you don't own any (show as unseized)

User page + ens

---

components/distribution-plan-tool/connect/distribution-plan-tool-connected.tsx
components/distribution-plan-tool/connect/distribution-plan-tool-not-connected.tsx
pages/distribution-plan-tool/index.tsx

Please note: tool name used here (EMMA) is not finalized, just a placeholder for what we land on.

Suggestions for AL builder tool sign-in page verbiage.

---

components/user/user-page-header/UserPageHeader.tsx
components/user/user-page-header/addresses/UserPageHeaderAddresses.tsx
pages/[user]/index.tsx
styles/globals.scss

1. profile addresses dropdow wrap down in smaller screens (better for mobile screenshots)
2. stagin ssr quickfix

Profile addresses responsive

---

components/delegation/CollectionDelegation.tsx

text changes/order delegation center

delegation center changes

---

components/latest-activity/LatestActivity.tsx
components/latest-activity/LatestActivityRow.tsx
components/nextGen/collections/NextGen.module.scss
components/nextGen/collections/collectionParts/NextGenCollectionArt.tsx
components/nextGen/collections/collectionParts/mint/NextgenCollectionMintingPlan.tsx
components/nextGen/collections/nextgenToken/NextGenTokenDownload.tsx
components/nextGen/collections/nextgenToken/NextGenTokenProperties.tsx
components/nextGen/nextgen_helpers.ts
components/pdfViewer/PdfViewer.tsx
components/react-query-wrapper/ReactQueryWrapper.tsx
components/user/collected/cards/UserPageCollectedCard.tsx
components/user/stats/activity/wallet/UserPageStatsActivityWallet.tsx
components/user/stats/activity/wallet/table/UserPageStatsActivityWalletTable.tsx
components/user/stats/activity/wallet/table/UserPageStatsActivityWalletTableWrapper.tsx
components/user/stats/activity/wallet/table/row/UserPageStatsActivityWalletTableRow.tsx
components/user/stats/tags/UserPageStatsTags.tsx
constants.ts
entities/ITDH.ts
styles/Home.module.scss
styles/globals.scss

- Adjust activity rows in nft activity and profile for nextgen
- include all contracts from /transactions endpoint in activity - memelab not included still
- nextgen tag

Nextgen Followup

---

components/about/About.module.scss
components/about/AboutMemesCalendar.tsx
helpers/time.ts

- Created AboutMemesCalendar component to display the Memes Seasonal Calendar
- Added styling for the calendar table in About.module.scss
- Integrated MEMES_CALENDARS data from meme_calendar.helpers
- Implemented active section highlighting based on current date
- Ensured responsive design for various screen sizes

Implement Memes Seasonal Calendar page

---

components/drops/create/lexical/plugins/DragDropPastePlugin.tsx

- fix DragDropPastePlugin to avoid updating editor after unmount
- `npx jest` *(fails: connect EHOSTUNREACH 172.25.0.3:8080)*

Fix lexical error when uploading images

---

__mocks__/nanoCssMock.js
__mocks__/react-use.js
__tests__/MemePageLive.test.tsx
__tests__/components/the-memes/MemePage.test.tsx
__tests__/components/the-memes/MemePageActivity.test.tsx
__tests__/components/waves/Waves.test.tsx
__tests__/components/waves/list/WavesList.test.tsx
__tests__/contexts/wave/hooks/useWavePagination.test.ts
contexts/wave/hooks/useWavePagination.ts
jest.config.js

- resolve merge artifacts in Jest config
- mock nano-css for react-use
- simplify react-use mock
- fix relative paths in tests
- fix failing tests and update pagination hook
- `npm test`

Fix Jest config and update mocks

---

.github/workflows/build-upload-deploy-prod.yml

Also updating workflow node version to 22

Update elastic beanstalk env name

---

__tests__/components/about/AboutApply.test.tsx
__tests__/components/about/AboutContactUs.test.tsx
__tests__/components/about/AboutCookiePolicy.test.tsx
__tests__/components/about/AboutCopyright.test.tsx
__tests__/components/about/AboutDataDecentral.test.tsx
__tests__/components/about/AboutGDRC1.test.tsx
__tests__/components/about/AboutGradients.test.tsx
__tests__/components/about/AboutHTML.test.tsx
__tests__/components/about/AboutLicense.test.tsx
__tests__/components/about/AboutMemeLab.test.tsx
__tests__/components/about/AboutMemes.test.tsx
review-pr.sh

- add comprehensive tests for About section components
- ensure external links, headings, and interactive elements work
- verify cookie consent toggle logic

Add about page tests

---

__tests__/components/brain/left-sidebar/BrainLeftSidebar.test.tsx
__tests__/components/brain/left-sidebar/waves/UnifiedWavesList.test.tsx

- add tests for BrainLeftSidebar component
- add tests for UnifiedWavesList

Increase test coverage

---

__tests__/components/brain/content/BrainContent.test.tsx
__tests__/components/brain/content/input/BrainContentInput.test.tsx
__tests__/components/brain/left-sidebar/waves/UnifiedWavesListWaves.test.tsx
__tests__/components/brain/mobile/BrainMobileAbout.test.tsx
__tests__/components/brain/my-stream/MyStream.test.tsx

- add tests for UnifiedWavesListWaves
- add tests for BrainMobileAbout component
- add tests for MyStream wrapper
- adjust existing tests for type correctness

Increase coverage with mobile tests

---

__tests__/components/brain/left-sidebar/search-wave/BrainLeftSidebarSearchWave.test.tsx

- add unit tests for BrainLeftSidebarSearchWave component

Add tests for BrainLeftSidebarSearchWave

---

__tests__/components/brain/my-stream/MyStreamWaveDesktopTabs.test.tsx
__tests__/components/brain/my-stream/MyStreamWaveTabsLeaderboard.test.tsx
__tests__/components/brain/my-stream/MyStreamWrapper.test.tsx

- add tests for MyStreamWaveDesktopTabs component
- add tests for MyStreamWaveTabsLeaderboard component
- add tests for MyStreamWrapper component

Add tests for MyStream components

---

__mocks__/AGENTS.md
__tests__/AGENTS.md
__tests__/components/distribution-plan-tool/build-phases/component-config/ComponentAddSpots.test.tsx

- document detailed instructions for writing tests and mocks
- fix `ComponentAddSpots` test import and expectation

Add testing and mocking guidelines

---

__tests__/components/distribution-plan-tool/create-snapshots/table/CreateSnapshotTable.test.tsx

- add tests for CreateSnapshotTable

Increase coverage for CreateSnapshotTable

---

__tests__/components/distribution-plan-tool/plans/DistributionPlanToolPlans.test.tsx

- add tests for DistributionPlanToolPlans component

Increase tests for DistributionPlanToolPlans

---

__tests__/components/datePickerModal/DatePickerModal.test.tsx

- add unit tests for DatePickerModal component
- `npm run test` *(fails: logs truncated)*

Increase test coverage for DatePickerModal

---

__tests__/components/distribution-plan-tool/CreateTablePhasesRow.test.tsx
__tests__/store/groupSlice.test.ts

- add tests for CreateTablePhasesRow component
- add unit tests for Redux groupSlice reducer
- `npm run test` *(fails: The suite is huge and there may be network issues)*

Add tests for CreateTablePhasesRow and groupSlice

---

__tests__/components/layout/AppLayout.test.tsx

- correct the import path in `AppLayout.test.tsx`

Fix AppLayout test import path

---

__tests__/components/groups/page/create/config/GroupCreateLevel.test.tsx

- correct relative paths in `GroupCreateLevel.test.tsx`

Fix test import paths for GroupCreateLevel

---

__mocks__/react-use.js
__tests__/components/groups/page/create/config/GroupCreateConfig.test.tsx
__tests__/components/groups/page/create/config/common/GroupCreateNumericValue.test.tsx

- add a mock for more react-use hooks
- add tests for `GroupCreateConfig`
- add tests for `GroupCreateNumericValue`

Add group create config tests

---

scripts/coverage_prompt.md
scripts/improve-coverage.js

- add option to suggest more low coverage files in `improve-coverage.js`
- clarify iterative workflow in `coverage_prompt.md`

Improve coverage workflow instructions

---

__tests__/components/header/share/HeaderQRScanner.test.tsx

- add tests for HeaderQRScanner component

Increase test coverage for QR scanner

---

__tests__/components/header/user/proxy/HeaderUserProxyDropdown.test.tsx
__tests__/components/user/groups/UserPageGroupsWrapper.test.tsx

- add tests for `HeaderUserProxyDropdown`
- fix typing in `UserPageGroupsWrapper` test

Increase coverage for dropdown component

---

__tests__/pages/userPageRep.test.tsx

- add tests for `pages/[user]/rep.tsx`

Add test coverage for rep page

---

.CLAUDE.md
__tests__/components/nextGen/collections/collectionParts/NextGenCollectionSlideshow.test.tsx
app/page.tsx
components/.CLAUDE.md
components/home/FeaturedNFTDetailsTable.tsx
components/home/LatestDropSection.tsx
components/home/ManifoldClaimTable.tsx
components/home/MintingApproachSection.tsx
components/nextGen/collections/collectionParts/NextGenCollectionSlideshow.tsx
helpers/manifoldDisplayHelpers.ts
hooks/useManifoldClaimDisplays.tsx
src/.CLAUDE.md

- Fixed unnecessary re-renders on the homepage by extracting components and adding memoization
- Optimized NextGen slideshow with lazy loading and intersection observer
- Improved code organization by extracting reusable components and utility functions
- **Component Extraction**: Split large LatestDropSection into smaller, focused components
- **Memoization**: Added React.memo to prevent unnecessary image re-downloads
- **Smart Data Fetching**: Implemented progressive loading in slideshow with configurable buffer sizes
- **Viewport Optimization**: Added intersection observer to control autoplay based on visibility
- **Code Reuse**: Created useManifoldClaimDisplays hook and manifold display helpers

# Performance Optimizations for Index Page
